site_name: lernOS Sewing Hero Guide
site_url: https://simondueckert.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Welcome: index.md
    - Basics:
      - Understanding your sewing machine: 1-1-Understanding_Your_Sewing_Machine.md
      - Fabrics and materials: 1-2-Fabrics_and_Materials.md
      - Basic sewing techniques: 1-3-Basic_Sewing_Techniques.md
      - Pattern reading: 1-4-Pattern_Reading.md
      - Sewing safety: 1-5-Sewing_Safety.md
    - Learning Pathway: 2-0-Learning-Pathway.md
    - Appendix: 3-0-Appendix.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-template/blob/master/de/build/lernos-sewing-hero-guide.pdf
      - Word-Version: https://github.com/cogneon/lernos-template/blob/master/de/build/lernos-sewing-hero-guide.docx
      - HTML-Version: https://github.com/cogneon/lernos-template/blob/master/de/build/lernos-sewing-hero-guide.html
      - E-Book (epub): https://github.com/cogneon/lernos-template/blob/master/de/build/lernos-sewing-hero-guide.epub
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - toc.integrate

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/matomo.js

repo_name: 'simondueckert/lernos-sewing-hero'
repo_url: 'https://github.com/simondueckert/lernos-sewing-hero'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    giscus: true
    generator: false

copyright: cogneon.de/impressum

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - rss:
      abstract_chars_count: -1  # -1 for full content